# Generated by Django 5.2.15 on 2026-07-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='jabatan',
            field=models.CharField(choices=[('Staff Produksi', 'Staff Produksi'), ('Operator Mesin', 'Operator Mesin'), ('Supervisor Produksi', 'Supervisor Produksi'), ('QA Analyst', 'QA Analyst'), ('QA Inspector', 'QA Inspector'), ('HR Officer', 'HR Officer'), ('Recruiter', 'Recruiter'), ('Marketing Executive', 'Marketing Executive'), ('Digital Marketing', 'Digital Marketing'), ('IT Support', 'IT Support'), ('Software Engineer', 'Software Engineer'), ('System Analyst', 'System Analyst'), ('Finance Staff', 'Finance Staff'), ('Accountant', 'Accountant'), ('Logistics Staff', 'Logistics Staff'), ('Warehouse Admin', 'Warehouse Admin')], max_length=100),
        ),
    ]
